name: Format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Replace genericpath.py
      working-directory: ./backend
      run: |
        sudo cp genericpath.py /usr/lib/python${{ matrix.python-version }}/genericpath.py
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black # TODO move this to requirements.txt
    - name: Check code formatting with black
      working-directory: ./backend
      run: |
        black --check $(git ls-files '*.py')
